//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendsSelection.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournament()
        {
            this.UserTournament = new HashSet<UserTournament>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> TournamentDateTime { get; set; }
        public int GameId { get; set; }
        public int AvaliableRequests { get; set; }
        public string FirstPlaceReward { get; set; }
        public string SecondPlaceReward { get; set; }
        public string ThirdPlaceReward { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTournament> UserTournament { get; set; }
    }
}
