//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendsSelection.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTournament
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int TournamentId { get; set; }
    
        public virtual Tournament Tournament { get; set; }
        public virtual User User { get; set; }
    }
}
